Update golanci-lint version in container to fix compilation error warnings
The latest version of the sdcli container throws a warning due to compilation
errors when running the `sdcli go lint` command. Here's an example:

```bash
docker run -ti \
        --mount src="/Users/bkrebsbach/work/code/go/src/github.com/asecurityteam/nexpose-asset-attributor",target="/go/src/github.com/asecurityteam/nexpose-asset-attributor",type="bind" \
        -w "/go/src/github.com/asecurityteam/nexpose-asset-attributor" \
        asecurityteam/sdcli:v1 go lint
WARN [runner/megacheck] Can't run megacheck because of compilation errors in packages [github.com/asecurityteam/nexpose-asset-attributor/pkg/domain github.com/asecurityteam/nexpose-asset-attributor github.com/asecurityteam/nexpose-asset-attributor/pkg/assetattributor [github.com/asecurityteam/nexpose-asset-attributor/pkg/assetattributor.test] github.com/asecurityteam/nexpose-asset-attributor/pkg/handlers/v1 [github.com/asecurityteam/nexpose-asset-attributor/pkg/handlers/v1.test]]: pkg/domain/alias.go:1: /usr/local/go/src/internal/bytealg/compare_amd64.s:5:1: illegal character U+0023 '#' and 130 more errors: run `golangci-lint run --no-config --disable-all -E typecheck` to see all errors
```

This appears to be a result of https://github.com/golangci/golangci-lint/issues/433, which was fixed in golangci-lint v1.16.0.